# Generated by Django 5.0.2 on 2024-11-18 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoo_user',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zoo_user',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='zoo_user',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='zoo_user',
            name='phone',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('booking_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('hotel_booking_date', models.DateField(auto_now_add=True)),
                ('hotel_booking_date_arrive', models.DateField()),
                ('hotel_booking_date_leave', models.DateField()),
                ('hotel_booking_adults', models.IntegerField(default=0)),
                ('hotel_booking_children', models.IntegerField(default=0)),
                ('hotel_booking_oap', models.IntegerField(default=0)),
                ('hotel_total_cost', models.FloatField(default=0)),
                ('hotel_points', models.IntegerField(default=0)),
                ('hotel_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
